#!/bin/sh
#
# $FreeBSD$

# PROVIDE: wamupd
# REQUIRE: DAEMON dnsextd
# KEYWORD: shutdown

. /etc/rc.subr

name=wamupd
rcvar=`set_rcvar`

load_rc_config ${name}

: ${wamupd_enable="NO"}
: ${wamupd_bin="/usr/local/sbin/wamupd"}
: ${wamupd_flags="-c /usr/local/etc/wamupd.yaml -A /usr/local/etc/avahi/services -a -i"}


extra_commands=status

start_cmd=wamupd_start
stop_cmd=wamupd_stop
status_cmd=wamupd_status

wamupd_start() {
    if checkyesno wamupd_enable; then
        echo "Starting wamupd."
	${wamupd_bin} start -- ${wamupd_flags}
    fi
}

wamupd_stop() {
    if checkyesno wamupd_enable; then
	echo "Stopping wamupd."
    	${wamupd_bin} stop
    fi
}

wamupd_status() {
    if checkyesno wamupd_enable; then
	${wamupd_bin} status
    fi
}

load_rc_config ${name}
run_rc_command "$1"
